name: Reprocessar Abril Manual
on: 
  workflow_dispatch: # Isso permite que você aperte um botão para rodar

jobs:
  reprocessar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install requests psycopg2-binary python-dotenv
      - name: Run script
        env:
          SAIPOS_TOKEN: ${{ secrets.SAIPOS_TOKEN }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: python reprocessar.py
